Curso_de_ASP_NET_Core_MVC/LanchesMac/LanchesMac/Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            //if (User.Identity.IsAuthenticated)
            //{
            return View();
            //}
            //return RedirectToAction("Login", "Account");
        }
    }
}

Curso_de_ASP_NET_Core_MVC/LanchesMac/LanchesMac/Controllers/LancheController.cs
using LanchesMac.Models;
using LanchesMac.Repositories.Interfaces;
using LanchesMac.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class LancheController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        public LancheController(ILancheRepository lancheRepository)
        {
            _lancheRepository = lancheRepository;
        }

        public IActionResult List(string categoria)
        {
            IEnumerable<Lanche> lanches;
            string categoriaAtual = string.Empty;

            if(string.IsNullOrEmpty(categoria))
            {
                lanches = _lancheRepository.Lanches.OrderBy(l => l.LancheId);
                categoriaAtual = "Todos os lanches";
            }
            else
            {
                //if (string.Equals("Normal", categoria, StringComparison.OrdinalIgnoreCase))
                //{
                //    lanches = _lancheRepository.Lanches
                //        .Where(l => l.Categoria.CategoriaNome.Equals("Normal"))
                //        .OrderBy(l => l.Nome);
                //}
                //else
                //{
                //    lanches = _lancheRepository.Lanches
                //       .Where(l => l.Categoria.CategoriaNome.Equals("Natural"))
                //       .OrderBy(l => l.Nome);
                //}
                lanches = _lancheRepository.Lanches
                          .Where(l => l.Categoria.CategoriaNome.Equals(categoria))
                          .OrderBy(c => c.Nome);

                categoriaAtual = categoria;
            }

            var lanchesListViewModel = new LancheListViewModel
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            };

            return View(lanchesListViewModel);
        }

        public IActionResult Details(int lancheId)
        {
            var lanche = _lancheRepository.Lanches.FirstOrDefault(l => l.LancheId == lancheId);
            return View(lanche);
        }      

        public ViewResult Search(string searchString)
        {
            IEnumerable<Lanche> lanches;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(searchString))
            {
                lanches = _lancheRepository.Lanches.OrderBy(p => p.LancheId);
                categoriaAtual = "Todos os Lanches";
            }
            else
            {
                 lanches = _lancheRepository.Lanches
                           .Where(p => p.Nome.ToLower().Contains(searchString.ToLower()));

                if (lanches.Any())
                    categoriaAtual = "Lanches";
                else
                    categoriaAtual = "Nenhum lanche foi encontrado";
            }

            return View("~/Views/Lanche/List.cshtml", new LancheListViewModel
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            });
        }
    }
}

Curso_de_ASP_NET_Core_MVC/LanchesMac/LanchesMac/Views/Shared/_Barra.cshtml
 <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/logo_lanche2-sfd.png" />
                    LanchesMac
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="nav navbar-nav navbar-right">
                       <li>@await Component.InvokeAsync("CarrinhoCompraResumo")</li>
                       <li>@await Component.InvokeAsync("CategoriaMenu")</li>
                       <li><a class="nav-link text-light" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a></li>
                       <li><a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                       <li>
                        <form class="navbar-form navbar-right" asp-controller="Lanche" asp-action="Search" method="get">
                          <div class="form-group">
                            <input type="text" class="form-control" placeholder="Procurar produto" name="searchString" value="@ViewData["searchString"]">
                          </div>
                        </form>
                        </li>
                        <li>
                        @await Html.PartialAsync("_LoginPartial")
                        </li>
                        <li>
                        @if(User.IsInRole("Admin"))
                        {
                            <a class="nav-link text-light" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a>
                        }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

Curso_de_ASP_NET_Core_MVC/LanchesMac/LanchesMac/Views/Shared/_BarraMenu.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
     <div class="container">
       <a class="navbar-brand" asp-area="" asp-controller="Home"asp-action="Index">
          <img src="~/images/logo_lanche2-sfd.png" asp-append-version="true" />
          LanchesMac
      </a>
     <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar"
     aria-controls="collapsibleNavbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
      <!-- Collapsible content -->
    <div class="navbar-collapse collapse" id="collapsibleNavbar" style="font-size: medium; font-weight: bold">
           <ul class="navbar-nav mr-auto">
               <li class="nav-item">@await Component.InvokeAsync("CategoriaMenu")</li>
                <li class="nav-item">
                  <form class="navbar-form navbar-right" asp-controller="Lanche" asp-action="Search" method="get">
                    <div class="form-group">
                       <input type="text" class="form-control" placeholder="Procurar produto" name="searchString" value="@ViewData["searchString"]">
                    </div>
                 </form>
                </li>
               <li class="nav-item"><a class="nav-link text-light" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a></li>
               <li class="nav-item"><a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
               <li class="nav-item">
                 @if(User.IsInRole("Admin"))
                 {
                    <a class="nav-link text-light" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a>
                 }
               </li>
              <li class="nav-item">@await Html.PartialAsync("_LoginPartial")</li>
              <li class="nav-item">@await Component.InvokeAsync("CarrinhoCompraResumo")</li>
          </ul>
    </div>
  </div>
 </nav>

Curso_de_ASP_NET_Core_MVC/LanchesMac/LanchesMac/Views/Shared/_Carousel.cshtml
<div id="carouselLanches" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="~/images/carousel11.jpg" class="d-block w-100" alt="">
    </div>
    <div class="carousel-item">
      <img src="~/images/carousel12.jpg" class="d-block w-100" alt="">
    </div>
    <div class="carousel-item">
      <img src="~/images/carousel13.jpg" class="d-block w-100" alt="">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselLanches" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselLanches" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

Curso_de_ASP_NET_Core_MVC/LanchesMac/LanchesMac/Views/Shared/_Footer.cshtml
<footer>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
     <div class="container">
         <div class="row">
             <div class="col-10 col-md-5 col-lg-5 offset-1" style="color: white">
                 <h4> &copy; 2021 - LanchesMac</h4>
                 <p class="text-justify">
                     Aqui você encontra aquele lanche gostoso que da água na boca.
                     Aquela sobremesa saborosa e para acompanhar a sua bebida preferida.
                     E se você é vegetariano também vai encontrar o lanche, sobremesa e bebida do seu gosto.
                 </p>
             </div>

             <div class="col-10 col-md-5 col-lg-5 offset-1" style="color: white">
                 <h4>Tem alguma dúvida ?</h4>
                 <ul class="list-unstyled">
                     <li class="py-1"> Av. Bueno de Andrade, 56 Setor-2 Quadra-7</li>
                     <li class="py-1"> +55- 999 9123 502</li>
                     <li class="py-1"> <a href="lanchesmac@hotmail.com" style="color: yellow">lanchesmac@hotmail.com</a></li>
                 </ul>
             </div>
         </div>
     </div>
    </nav>
</footer>

Curso_de_ASP_NET_Core_MVC/LanchesMac/LanchesMac/Views/Shared/_LanchesResumo.cshtml
@model Lanche

<div class="col-sm-4 col-md-4 col-lg-4">
    <p><img src="@Model.ImagemUrl" class="img-fluid" asp-append-version="true"></p>
    <h3>Preço : @Model.Preco.ToString("c")</h3>

    <h4>
    <a asp-controller="Lanche" asp-action="Details" 
    asp-route-lancheId="@Model.LancheId">@Model.Nome</a>
    </h4>

    <p>@Model.DescricaoCurta</p>
      <div>
        <p class="button">
            <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoCompra" 
            asp-action="AdicionarItemNoCarrinhoCompra" asp-route-LancheId="@Model.LancheId">
            Incluir no Carrinho
        </a>
        </p>
    </div>

</div>

Curso_de_ASP_NET_Core_MVC/LanchesMac/LanchesMac/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LanchesMac</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <div>
         <partial name="_BarraMenu.cshtml" />
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

  @*  <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LanchesMac 
        </div>
    </footer>*@
    <div>
     <partial name="_Footer"/>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>